
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowLatent`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2024, 
        `title`="snowLatent: Latent Class Analysis for jamovi", 
        `publisher`="(Version 2.4.1) [jamovi module]. URL https://github.com/hyunsooseol/snowLatent", 
        `url`="https://github.com/hyunsooseol/snowLatent"), 
    `glca`=list(
        `type`="software", 
        `author`="Kim, Y., Chung, H.", 
        `year`=2021, 
        `title`="glca: An R Package for Multiple-Group Latent Class Analysis", 
        `publisher`="(Version 1.3.3) [R package]. URL https://CRAN.R-project.org/package=glca"))
