
# This file is automatically generated, you probably don't want to edit this

glcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            nc = 2,
            nb = 100,
            comp = TRUE,
            cp = FALSE,
            item = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="glca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=1,
                default=2)
            private$..nb <- jmvcore::OptionInteger$new(
                "nb",
                nb,
                min=10,
                default=100)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=TRUE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..post <- jmvcore::OptionOutput$new(
                "post")
            private$..item <- jmvcore::OptionBool$new(
                "item",
                item,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..nc)
            self$.addOption(private$..nb)
            self$.addOption(private$..comp)
            self$.addOption(private$..cp)
            self$.addOption(private$..post)
            self$.addOption(private$..item)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        nc = function() private$..nc$value,
        nb = function() private$..nb$value,
        comp = function() private$..comp$value,
        cp = function() private$..cp$value,
        post = function() private$..post$value,
        item = function() private$..item$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..nc = NA,
        ..nb = NA,
        ..comp = NA,
        ..cp = NA,
        ..post = NA,
        ..item = NA,
        ..plot1 = NA)
)

glcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        comp = function() private$.items[["comp"]],
        cp = function() private$.items[["cp"]],
        post = function() private$.items[["post"]],
        text1 = function() private$.items[["text1"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Group LCA")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Model fit",
                visible="(comp)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Class", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="Res.df", 
                        `type`="number"),
                    list(
                        `name`="gsq", 
                        `title`="Gsq", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Size of each latent class",
                visible="(cp)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="post",
                title="Posterior probabilities",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Item-response probabilities"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                width=700,
                height=700,
                renderFun=".plot1",
                visible="(plot1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb")))}))

glcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "glca",
                version = c(1,0,0),
                options = options,
                results = glcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multiple Group LCA
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param group .
#' @param nc .
#' @param nb .
#' @param comp .
#' @param cp .
#' @param item .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$post} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$comp$asDF}
#'
#' \code{as.data.frame(results$comp)}
#'
#' @export
glca <- function(
    data,
    vars,
    group,
    nc = 2,
    nb = 100,
    comp = TRUE,
    cp = FALSE,
    item = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("glca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- glcaOptions$new(
        vars = vars,
        group = group,
        nc = nc,
        nb = nb,
        comp = comp,
        cp = cp,
        item = item,
        plot1 = plot1)

    analysis <- glcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

