
# This file is automatically generated, you probably don't want to edit this

glcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            covs = NULL,
            nc = 2,
            nb = 50,
            fit = TRUE,
            comp = FALSE,
            rel = FALSE,
            mi = FALSE,
            ci = FALSE,
            marginal = FALSE,
            preval = FALSE,
            post = TRUE,
            item = TRUE,
            co = TRUE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="glca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..nb <- jmvcore::OptionInteger$new(
                "nb",
                nb,
                min=10,
                default=50)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=FALSE)
            private$..rel <- jmvcore::OptionBool$new(
                "rel",
                rel,
                default=FALSE)
            private$..mi <- jmvcore::OptionBool$new(
                "mi",
                mi,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..marginal <- jmvcore::OptionBool$new(
                "marginal",
                marginal,
                default=FALSE)
            private$..preval <- jmvcore::OptionBool$new(
                "preval",
                preval,
                default=FALSE)
            private$..post <- jmvcore::OptionBool$new(
                "post",
                post,
                default=TRUE)
            private$..item <- jmvcore::OptionBool$new(
                "item",
                item,
                default=TRUE)
            private$..co <- jmvcore::OptionBool$new(
                "co",
                co,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..covs)
            self$.addOption(private$..nc)
            self$.addOption(private$..nb)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp)
            self$.addOption(private$..rel)
            self$.addOption(private$..mi)
            self$.addOption(private$..ci)
            self$.addOption(private$..marginal)
            self$.addOption(private$..preval)
            self$.addOption(private$..post)
            self$.addOption(private$..item)
            self$.addOption(private$..co)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        covs = function() private$..covs$value,
        nc = function() private$..nc$value,
        nb = function() private$..nb$value,
        fit = function() private$..fit$value,
        comp = function() private$..comp$value,
        rel = function() private$..rel$value,
        mi = function() private$..mi$value,
        ci = function() private$..ci$value,
        marginal = function() private$..marginal$value,
        preval = function() private$..preval$value,
        post = function() private$..post$value,
        item = function() private$..item$value,
        co = function() private$..co$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..covs = NA,
        ..nc = NA,
        ..nb = NA,
        ..fit = NA,
        ..comp = NA,
        ..rel = NA,
        ..mi = NA,
        ..ci = NA,
        ..marginal = NA,
        ..preval = NA,
        ..post = NA,
        ..item = NA,
        ..co = NA,
        ..plot1 = NA)
)

glcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        fit = function() private$.items[["fit"]],
        comp = function() private$.items[["comp"]],
        rel = function() private$.items[["rel"]],
        mi = function() private$.items[["mi"]],
        ci = function() private$.items[["ci"]],
        marginal = function() private$.items[["marginal"]],
        preval = function() private$.items[["preval"]],
        plot1 = function() private$.items[["plot1"]],
        text3 = function() private$.items[["text3"]],
        text1 = function() private$.items[["text1"]],
        text2 = function() private$.items[["text2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Group LCA")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                refs="glca",
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Absolute model fit",
                visible="(comp)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rel",
                title="Relative model fit(Class>2)",
                visible="(rel)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mi",
                title="Measurement invariance",
                visible="(mi)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ci",
                title="Equality of coefficients",
                visible="(ci)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="marginal",
                title="Marginal prevalences for latent classes",
                visible="(marginal)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="preval",
                title="Class prevalences by group",
                refs="glca",
                visible="(preval)",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                width=700,
                height=700,
                renderFun=".plot1",
                visible="(plot1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text3",
                title="Logistic regression"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Item-response probabilities"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Posterior probabilities"))}))

glcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "glcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "glca",
                version = c(1,0,0),
                options = options,
                results = glcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multiple Group LCA
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param group .
#' @param covs .
#' @param nc .
#' @param nb .
#' @param fit .
#' @param comp .
#' @param rel .
#' @param mi .
#' @param ci .
#' @param marginal .
#' @param preval .
#' @param post .
#' @param item .
#' @param co .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$marginal} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$preval} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text3} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
glca <- function(
    data,
    vars,
    group,
    covs,
    nc = 2,
    nb = 50,
    fit = TRUE,
    comp = FALSE,
    rel = FALSE,
    mi = FALSE,
    ci = FALSE,
    marginal = FALSE,
    preval = FALSE,
    post = TRUE,
    item = TRUE,
    co = TRUE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("glca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in covs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- glcaOptions$new(
        vars = vars,
        group = group,
        covs = covs,
        nc = nc,
        nb = nb,
        fit = fit,
        comp = comp,
        rel = rel,
        mi = mi,
        ci = ci,
        marginal = marginal,
        preval = preval,
        post = post,
        item = item,
        co = co,
        plot1 = plot1)

    analysis <- glcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

