
# This file is automatically generated, you probably don't want to edit this

lcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            class = 2,
            cluster = 1,
            summary = TRUE, ...) {

            super$initialize(
                package="snowLatent",
                name="lca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..class <- jmvcore::OptionInteger$new(
                "class",
                class,
                min=2,
                default=2)
            private$..cluster <- jmvcore::OptionInteger$new(
                "cluster",
                cluster,
                min=1,
                default=1)
            private$..summary <- jmvcore::OptionBool$new(
                "summary",
                summary,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..class)
            self$.addOption(private$..cluster)
            self$.addOption(private$..summary)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        class = function() private$..class$value,
        cluster = function() private$..cluster$value,
        summary = function() private$..summary$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..class = NA,
        ..cluster = NA,
        ..summary = NA)
)

lcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        instructions = function() private$.items[["instructions"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Class Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Latent Class Analysis"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))}))

lcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "lca",
                version = c(1,0,0),
                options = options,
                results = lcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Latent Class Analysis
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param group .
#' @param class .
#' @param cluster .
#' @param summary .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
lca <- function(
    data,
    vars,
    group,
    class = 2,
    cluster = 1,
    summary = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lcaOptions$new(
        vars = vars,
        group = group,
        class = class,
        cluster = cluster,
        summary = summary)

    analysis <- lcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

