
# This file is automatically generated, you probably don't want to edit this

lcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covs = NULL,
            nc = 2,
            nb = 50,
            fit = TRUE,
            comp = FALSE,
            rel = FALSE,
            cp = FALSE,
            item = FALSE,
            gamma = FALSE,
            coef = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            angle = 0,
            plot3 = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="lca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..nb <- jmvcore::OptionInteger$new(
                "nb",
                nb,
                min=10,
                default=50)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp <- jmvcore::OptionBool$new(
                "comp",
                comp,
                default=FALSE)
            private$..rel <- jmvcore::OptionBool$new(
                "rel",
                rel,
                default=FALSE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..post <- jmvcore::OptionOutput$new(
                "post")
            private$..member <- jmvcore::OptionOutput$new(
                "member")
            private$..item <- jmvcore::OptionBool$new(
                "item",
                item,
                default=FALSE)
            private$..gamma <- jmvcore::OptionBool$new(
                "gamma",
                gamma,
                default=FALSE)
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..covs)
            self$.addOption(private$..nc)
            self$.addOption(private$..nb)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp)
            self$.addOption(private$..rel)
            self$.addOption(private$..cp)
            self$.addOption(private$..post)
            self$.addOption(private$..member)
            self$.addOption(private$..item)
            self$.addOption(private$..gamma)
            self$.addOption(private$..coef)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot3)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
        }),
    active = list(
        vars = function() private$..vars$value,
        covs = function() private$..covs$value,
        nc = function() private$..nc$value,
        nb = function() private$..nb$value,
        fit = function() private$..fit$value,
        comp = function() private$..comp$value,
        rel = function() private$..rel$value,
        cp = function() private$..cp$value,
        post = function() private$..post$value,
        member = function() private$..member$value,
        item = function() private$..item$value,
        gamma = function() private$..gamma$value,
        coef = function() private$..coef$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        angle = function() private$..angle$value,
        plot3 = function() private$..plot3$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value),
    private = list(
        ..vars = NA,
        ..covs = NA,
        ..nc = NA,
        ..nb = NA,
        ..fit = NA,
        ..comp = NA,
        ..rel = NA,
        ..cp = NA,
        ..post = NA,
        ..member = NA,
        ..item = NA,
        ..gamma = NA,
        ..coef = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..angle = NA,
        ..plot3 = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA)
)

lcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        fit = function() private$.items[["fit"]],
        comp = function() private$.items[["comp"]],
        rel = function() private$.items[["rel"]],
        cp = function() private$.items[["cp"]],
        coef = function() private$.items[["coef"]],
        item = function() private$.items[["item"]],
        post = function() private$.items[["post"]],
        member = function() private$.items[["member"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        text2 = function() private$.items[["text2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Class Analysis",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "covs",
                    "nb"),
                refs="glca",
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp",
                title="Absolute model fit",
                visible="(comp)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rel",
                title="Relative model fit(Class>2)",
                visible="(rel)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cp",
                title="Marginal prevalences for latent class",
                visible="(cp)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="Logistic regression coefficients",
                visible="(coef)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="odds", 
                        `title`="Odds ratio", 
                        `type`="number"),
                    list(
                        `name`="co", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="error", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="item",
                title="Item response probabilities",
                visible="(item)",
                items="(vars)",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Probability of $key",
                    clearWith=list(
                        "vars",
                        "covs",
                        "nc",
                        "nb"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Output$new(
                options=options,
                name="post",
                title="Posterior probabilities",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb")))
            self$add(jmvcore::Output$new(
                options=options,
                name="member",
                title="Class membership",
                measureType="nominal",
                varTitle="Membership",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                renderFun=".plot1",
                visible="(plot1)",
                refs="glca",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Item by class",
                renderFun=".plot2",
                visible="(plot2)",
                refs="snowLatent",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb",
                    "angle",
                    "width1",
                    "height1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Elbow plot",
                visible="(plot3)",
                refs="snowLatent",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb",
                    "width2",
                    "height2")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Prevalence for level-1 class(Gamma)"))}))

lcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "lca",
                version = c(1,0,0),
                options = options,
                results = lcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Latent Class Analysis
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param covs .
#' @param nc .
#' @param nb .
#' @param fit .
#' @param comp .
#' @param rel .
#' @param cp .
#' @param item .
#' @param gamma .
#' @param coef .
#' @param plot1 .
#' @param plot2 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot3 .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rel} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$post} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$member} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
lca <- function(
    data,
    vars,
    covs,
    nc = 2,
    nb = 50,
    fit = TRUE,
    comp = FALSE,
    rel = FALSE,
    cp = FALSE,
    item = FALSE,
    gamma = FALSE,
    coef = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    angle = 0,
    plot3 = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covs), covs, NULL))


    options <- lcaOptions$new(
        vars = vars,
        covs = covs,
        nc = nc,
        nb = nb,
        fit = fit,
        comp = comp,
        rel = rel,
        cp = cp,
        item = item,
        gamma = gamma,
        coef = coef,
        plot1 = plot1,
        plot2 = plot2,
        angle = angle,
        plot3 = plot3,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2)

    analysis <- lcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

