
# This file is automatically generated, you probably don't want to edit this

ltaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covs = NULL,
            form1 = "lc(6) ~ ESMK_98+FSMK_98+DSMK_98+HSMK_98+EDRK_98+CDRK_98+WDRK_98+BDRK_98+EMRJ_98+CMRJ_98+OMRJ_98+SMRJ_98",
            form2 = "lc ~ SEX",
            method = "naive",
            fit = FALSE,
            est = FALSE,
            desc = TRUE,
            cp = FALSE,
            plot1 = FALSE,
            plot = FALSE,
            raw = "FALSE",
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="lta",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..form1 <- jmvcore::OptionString$new(
                "form1",
                form1,
                default="lc(6) ~ ESMK_98+FSMK_98+DSMK_98+HSMK_98+EDRK_98+CDRK_98+WDRK_98+BDRK_98+EMRJ_98+CMRJ_98+OMRJ_98+SMRJ_98")
            private$..form2 <- jmvcore::OptionString$new(
                "form2",
                form2,
                default="lc ~ SEX")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "naive",
                    "BCH",
                    "ML"),
                default="naive")
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..est <- jmvcore::OptionBool$new(
                "est",
                est,
                default=FALSE)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=TRUE)
            private$..cp <- jmvcore::OptionBool$new(
                "cp",
                cp,
                default=FALSE)
            private$..mem <- jmvcore::OptionOutput$new(
                "mem")
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..raw <- jmvcore::OptionList$new(
                "raw",
                raw,
                options=list(
                    "FALSE",
                    "TRUE"),
                default="FALSE")
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..covs)
            self$.addOption(private$..form1)
            self$.addOption(private$..form2)
            self$.addOption(private$..method)
            self$.addOption(private$..fit)
            self$.addOption(private$..est)
            self$.addOption(private$..desc)
            self$.addOption(private$..cp)
            self$.addOption(private$..mem)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot)
            self$.addOption(private$..raw)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        covs = function() private$..covs$value,
        form1 = function() private$..form1$value,
        form2 = function() private$..form2$value,
        method = function() private$..method$value,
        fit = function() private$..fit$value,
        est = function() private$..est$value,
        desc = function() private$..desc$value,
        cp = function() private$..cp$value,
        mem = function() private$..mem$value,
        plot1 = function() private$..plot1$value,
        plot = function() private$..plot$value,
        raw = function() private$..raw$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..covs = NA,
        ..form1 = NA,
        ..form2 = NA,
        ..method = NA,
        ..fit = NA,
        ..est = NA,
        ..desc = NA,
        ..cp = NA,
        ..mem = NA,
        ..plot1 = NA,
        ..plot = NA,
        ..raw = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA)
)

ltaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text1 = function() private$.items[["text1"]],
        text2 = function() private$.items[["text2"]],
        text3 = function() private$.items[["text3"]],
        text4 = function() private$.items[["text4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Transition Analysis",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Coefficients"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Standard errors"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text3",
                title="Wald"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text4",
                title="p value"))}))

ltaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "lta",
                version = c(1,0,0),
                options = options,
                results = ltaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Latent Transition Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param covs .
#' @param form1 .
#' @param form2 .
#' @param method .
#' @param fit .
#' @param est .
#' @param desc .
#' @param cp .
#' @param plot1 .
#' @param plot .
#' @param raw .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text3} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text4} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
lta <- function(
    data,
    vars,
    covs,
    form1 = "lc(6) ~ ESMK_98+FSMK_98+DSMK_98+HSMK_98+EDRK_98+CDRK_98+WDRK_98+BDRK_98+EMRJ_98+CMRJ_98+OMRJ_98+SMRJ_98",
    form2 = "lc ~ SEX",
    method = "naive",
    fit = FALSE,
    est = FALSE,
    desc = TRUE,
    cp = FALSE,
    plot1 = FALSE,
    plot = FALSE,
    raw = "FALSE",
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lta requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ltaOptions$new(
        vars = vars,
        covs = covs,
        form1 = form1,
        form2 = form2,
        method = method,
        fit = fit,
        est = est,
        desc = desc,
        cp = cp,
        plot1 = plot1,
        plot = plot,
        raw = raw,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1)

    analysis <- ltaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

