
# This file is automatically generated, you probably don't want to edit this

ltaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(
                list(label="L1[2]", vars=list())),
            covs = NULL,
            regform = "pf ~ SEX+RACE",
            impu = "modal",
            method = "BCH",
            cons = "L1,L2,L3",
            reg = FALSE,
            par2 = FALSE,
            par3 = FALSE,
            fit1 = FALSE,
            plot = FALSE,
            width = 500,
            height = 500,
            plot1 = FALSE,
            plot2 = FALSE,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500,
            tau = FALSE,
            stayer = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="lta",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(
                    list(label="L1[2]", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "nominal",
                                "continuous"),
                            permitted=list(
                                "factor",
                                "numeric")))))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..regform <- jmvcore::OptionString$new(
                "regform",
                regform,
                default="pf ~ SEX+RACE")
            private$..impu <- jmvcore::OptionList$new(
                "impu",
                impu,
                options=list(
                    "modal",
                    "prob"),
                default="modal")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "naive",
                    "BCH",
                    "ML"),
                default="BCH")
            private$..cons <- jmvcore::OptionString$new(
                "cons",
                cons,
                default="L1,L2,L3")
            private$..reg <- jmvcore::OptionBool$new(
                "reg",
                reg,
                default=FALSE)
            private$..par2 <- jmvcore::OptionBool$new(
                "par2",
                par2,
                default=FALSE)
            private$..par3 <- jmvcore::OptionBool$new(
                "par3",
                par3,
                default=FALSE)
            private$..fit1 <- jmvcore::OptionBool$new(
                "fit1",
                fit1,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..tau <- jmvcore::OptionBool$new(
                "tau",
                tau,
                default=FALSE)
            private$..stayer <- jmvcore::OptionBool$new(
                "stayer",
                stayer,
                default=FALSE)

            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..regform)
            self$.addOption(private$..impu)
            self$.addOption(private$..method)
            self$.addOption(private$..cons)
            self$.addOption(private$..reg)
            self$.addOption(private$..par2)
            self$.addOption(private$..par3)
            self$.addOption(private$..fit1)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..tau)
            self$.addOption(private$..stayer)
        }),
    active = list(
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        regform = function() private$..regform$value,
        impu = function() private$..impu$value,
        method = function() private$..method$value,
        cons = function() private$..cons$value,
        reg = function() private$..reg$value,
        par2 = function() private$..par2$value,
        par3 = function() private$..par3$value,
        fit1 = function() private$..fit1$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        tau = function() private$..tau$value,
        stayer = function() private$..stayer$value),
    private = list(
        ..factors = NA,
        ..covs = NA,
        ..regform = NA,
        ..impu = NA,
        ..method = NA,
        ..cons = NA,
        ..reg = NA,
        ..par2 = NA,
        ..par3 = NA,
        ..fit1 = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..tau = NA,
        ..stayer = NA)
)

ltaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        fit1 = function() private$.items[["fit1"]],
        text3 = function() private$.items[["text3"]],
        text4 = function() private$.items[["text4"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        tau = function() private$.items[["tau"]],
        stay = function() private$.items[["stay"]],
        reg = function() private$.items[["reg"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Latent Transition Analysis",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit1",
                title="Testing for measurement invariance ",
                visible="(fit1)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc",
                    "cons"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="res", 
                        `title`="Residual df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text3",
                title="LTA with non-invariant model"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text4",
                title="LTA with measurement invariance"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Transition plot(Non-invariant)",
                renderFun=".plot1",
                visible="(plot1)",
                requiresData=TRUE,
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc",
                    "width1",
                    "height1",
                    "cons")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Transition plot(Invariant)",
                renderFun=".plot2",
                visible="(plot2)",
                requiresData=TRUE,
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc",
                    "width2",
                    "height2",
                    "cons")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tau",
                title="Transition probabilities",
                visible="(tau)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc",
                    "cons"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="transition", 
                        `title`="Transition", 
                        `type`="text"),
                    list(
                        `name`="from", 
                        `title`="From", 
                        `type`="text"),
                    list(
                        `name`="to", 
                        `title`="To", 
                        `type`="text"),
                    list(
                        `name`="prob", 
                        `title`="Prob", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="stay",
                title="Classification stability (Mean diagonal of transition matrix)",
                visible="(stayer)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc",
                    "cons"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="transition", 
                        `title`="Transition", 
                        `type`="text"),
                    list(
                        `name`="stayer", 
                        `title`="Average stay probability", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="mover", 
                        `title`="Average switching probability", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="reg",
                title="Logistic regression",
                visible="(reg)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "covs",
                    "nc",
                    "method",
                    "impu",
                    "regform",
                    "cons"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cla", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="va", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="co", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std.error", 
                        `type`="number"),
                    list(
                        `name`="wald", 
                        `title`="Wald", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Covariate effects plot",
                renderFun=".plot",
                visible="(plot)",
                requiresData=TRUE,
                clearWith=list(
                    "factors",
                    "covs",
                    "nc",
                    "method",
                    "impu",
                    "regform",
                    "width",
                    "height",
                    "cons")))}))

ltaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ltaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "lta",
                version = c(1,0,0),
                options = options,
                results = ltaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Latent Transition Analysis
#'
#' 
#' @param data .
#' @param factors a list containing named lists that define the \code{label}
#'   of the factor and the \code{vars} that belong to that factor
#' @param covs .
#' @param regform .
#' @param impu .
#' @param method .
#' @param cons .
#' @param reg .
#' @param par2 .
#' @param par3 .
#' @param fit1 .
#' @param plot .
#' @param width .
#' @param height .
#' @param plot1 .
#' @param plot2 .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @param tau .
#' @param stayer .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text3} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text4} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tau} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stay} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit1$asDF}
#'
#' \code{as.data.frame(results$fit1)}
#'
#' @export
lta <- function(
    data,
    factors = list(
                list(label="L1[2]", vars=list())),
    covs,
    regform = "pf ~ SEX+RACE",
    impu = "modal",
    method = "BCH",
    cons = "L1,L2,L3",
    reg = FALSE,
    par2 = FALSE,
    par3 = FALSE,
    fit1 = FALSE,
    plot = FALSE,
    width = 500,
    height = 500,
    plot1 = FALSE,
    plot2 = FALSE,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500,
    tau = FALSE,
    stayer = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lta requires jmvcore to be installed (restart may be required)")

    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(covs), covs, NULL))


    options <- ltaOptions$new(
        factors = factors,
        covs = covs,
        regform = regform,
        impu = impu,
        method = method,
        cons = cons,
        reg = reg,
        par2 = par2,
        par3 = par3,
        fit1 = fit1,
        plot = plot,
        width = width,
        height = height,
        plot1 = plot1,
        plot2 = plot2,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2,
        tau = tau,
        stayer = stayer)

    analysis <- ltaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

