
# This file is automatically generated, you probably don't want to edit this

mlcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covs = NULL,
            group = NULL,
            nc = 2,
            nclust = 2,
            fit = TRUE,
            comp1 = FALSE,
            rel1 = FALSE,
            cla = FALSE,
            cross = FALSE,
            mpc = FALSE,
            cpc = FALSE,
            cn = FALSE,
            co = FALSE,
            gof = FALSE,
            ci = FALSE,
            item = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            angle = 0,
            plot3 = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="mlca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..nclust <- jmvcore::OptionInteger$new(
                "nclust",
                nclust,
                min=2,
                default=2)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp1 <- jmvcore::OptionBool$new(
                "comp1",
                comp1,
                default=FALSE)
            private$..rel1 <- jmvcore::OptionBool$new(
                "rel1",
                rel1,
                default=FALSE)
            private$..cla <- jmvcore::OptionBool$new(
                "cla",
                cla,
                default=FALSE)
            private$..cross <- jmvcore::OptionBool$new(
                "cross",
                cross,
                default=FALSE)
            private$..mpc <- jmvcore::OptionBool$new(
                "mpc",
                mpc,
                default=FALSE)
            private$..cpc <- jmvcore::OptionBool$new(
                "cpc",
                cpc,
                default=FALSE)
            private$..cn <- jmvcore::OptionBool$new(
                "cn",
                cn,
                default=FALSE)
            private$..co <- jmvcore::OptionBool$new(
                "co",
                co,
                default=FALSE)
            private$..gof <- jmvcore::OptionBool$new(
                "gof",
                gof,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..item <- jmvcore::OptionBool$new(
                "item",
                item,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..covs)
            self$.addOption(private$..group)
            self$.addOption(private$..nc)
            self$.addOption(private$..nclust)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp1)
            self$.addOption(private$..rel1)
            self$.addOption(private$..cla)
            self$.addOption(private$..cross)
            self$.addOption(private$..mpc)
            self$.addOption(private$..cpc)
            self$.addOption(private$..cn)
            self$.addOption(private$..co)
            self$.addOption(private$..gof)
            self$.addOption(private$..ci)
            self$.addOption(private$..item)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot3)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
        }),
    active = list(
        vars = function() private$..vars$value,
        covs = function() private$..covs$value,
        group = function() private$..group$value,
        nc = function() private$..nc$value,
        nclust = function() private$..nclust$value,
        fit = function() private$..fit$value,
        comp1 = function() private$..comp1$value,
        rel1 = function() private$..rel1$value,
        cla = function() private$..cla$value,
        cross = function() private$..cross$value,
        mpc = function() private$..mpc$value,
        cpc = function() private$..cpc$value,
        cn = function() private$..cn$value,
        co = function() private$..co$value,
        gof = function() private$..gof$value,
        ci = function() private$..ci$value,
        item = function() private$..item$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        angle = function() private$..angle$value,
        plot3 = function() private$..plot3$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value),
    private = list(
        ..vars = NA,
        ..covs = NA,
        ..group = NA,
        ..nc = NA,
        ..nclust = NA,
        ..fit = NA,
        ..comp1 = NA,
        ..rel1 = NA,
        ..cla = NA,
        ..cross = NA,
        ..mpc = NA,
        ..cpc = NA,
        ..cn = NA,
        ..co = NA,
        ..gof = NA,
        ..ci = NA,
        ..item = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..angle = NA,
        ..plot3 = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA)
)

mlcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        fit = function() private$.items[["fit"]],
        comp1 = function() private$.items[["comp1"]],
        rel1 = function() private$.items[["rel1"]],
        cn = function() private$.items[["cn"]],
        cla = function() private$.items[["cla"]],
        cross = function() private$.items[["cross"]],
        mpc = function() private$.items[["mpc"]],
        cpc = function() private$.items[["cpc"]],
        gof = function() private$.items[["gof"]],
        ci = function() private$.items[["ci"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        item = function() private$.items[["item"]],
        text3 = function() private$.items[["text3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel LCA",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                refs="glca",
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp1",
                title="Absolute model fit for cluster",
                visible="(comp1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rel1",
                title="Relative model fit for cluster",
                visible="(rel1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="number"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cn",
                title="Cluster membership",
                visible="(cn)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cla",
                title="Marginal prevalences for latent classes",
                refs="glca",
                visible="(cla)",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cross",
                title="Class prevalences by group",
                refs="glca",
                visible="(cross)",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mpc",
                title="Marginal prevalences for latent clusters",
                refs="glca",
                visible="(mpc)",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cpc",
                title="Class prevalences by clusters",
                refs="glca",
                visible="(cpc)",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="gof",
                title="Goodness of fit for coefficients",
                visible="(gof)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ci",
                title="Equality of coefficients",
                visible="(ci)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                renderFun=".plot1",
                visible="(plot1)",
                refs="glca",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Item by class",
                renderFun=".plot2",
                visible="(plot2)",
                refs="snowLatent",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust",
                    "angle",
                    "width1",
                    "height1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Elbow plot",
                visible="(plot3)",
                refs="snowLatent",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "nc",
                    "group",
                    "covs",
                    "nclust",
                    "width2",
                    "height2")))
            self$add(jmvcore::Array$new(
                options=options,
                name="item",
                title="Item response probability(Rho)",
                visible="(item)",
                items="(vars)",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "group",
                    "nclust"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Probability of $key",
                    clearWith=list(
                        "vars",
                        "covs",
                        "nc",
                        "group",
                        "nclust"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text3",
                title="Logistic regression"))}))

mlcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "mlca",
                version = c(1,0,0),
                options = options,
                results = mlcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multilevel LCA
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param covs .
#' @param group .
#' @param nc .
#' @param nclust .
#' @param fit .
#' @param comp1 .
#' @param rel1 .
#' @param cla .
#' @param cross .
#' @param mpc .
#' @param cpc .
#' @param cn .
#' @param co .
#' @param gof .
#' @param ci .
#' @param item .
#' @param plot1 .
#' @param plot2 .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot3 .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rel1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cn} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cla} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cross} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mpc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cpc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gof} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$item} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$text3} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
mlca <- function(
    data,
    vars,
    covs,
    group,
    nc = 2,
    nclust = 2,
    fit = TRUE,
    comp1 = FALSE,
    rel1 = FALSE,
    cla = FALSE,
    cross = FALSE,
    mpc = FALSE,
    cpc = FALSE,
    cn = FALSE,
    co = FALSE,
    gof = FALSE,
    ci = FALSE,
    item = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    angle = 0,
    plot3 = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mlca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mlcaOptions$new(
        vars = vars,
        covs = covs,
        group = group,
        nc = nc,
        nclust = nclust,
        fit = fit,
        comp1 = comp1,
        rel1 = rel1,
        cla = cla,
        cross = cross,
        mpc = mpc,
        cpc = cpc,
        cn = cn,
        co = co,
        gof = gof,
        ci = ci,
        item = item,
        plot1 = plot1,
        plot2 = plot2,
        angle = angle,
        plot3 = plot3,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2)

    analysis <- mlcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

