
# This file is automatically generated, you probably don't want to edit this

mlcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covs = NULL,
            group = NULL,
            nc = 2,
            nclust = 2,
            nb = 10,
            fit = TRUE,
            comp1 = FALSE,
            rel1 = FALSE,
            margin = FALSE,
            cla = FALSE,
            cross = FALSE,
            co = FALSE,
            gof = FALSE,
            ci = FALSE,
            item = FALSE,
            post = FALSE,
            gamma = FALSE,
            member = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="mlca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nc <- jmvcore::OptionInteger$new(
                "nc",
                nc,
                min=2,
                default=2)
            private$..nclust <- jmvcore::OptionInteger$new(
                "nclust",
                nclust,
                min=2,
                default=2)
            private$..nb <- jmvcore::OptionInteger$new(
                "nb",
                nb,
                min=10,
                default=10)
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=TRUE)
            private$..comp1 <- jmvcore::OptionBool$new(
                "comp1",
                comp1,
                default=FALSE)
            private$..rel1 <- jmvcore::OptionBool$new(
                "rel1",
                rel1,
                default=FALSE)
            private$..margin <- jmvcore::OptionBool$new(
                "margin",
                margin,
                default=FALSE)
            private$..cla <- jmvcore::OptionBool$new(
                "cla",
                cla,
                default=FALSE)
            private$..cross <- jmvcore::OptionBool$new(
                "cross",
                cross,
                default=FALSE)
            private$..co <- jmvcore::OptionBool$new(
                "co",
                co,
                default=FALSE)
            private$..gof <- jmvcore::OptionBool$new(
                "gof",
                gof,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..item <- jmvcore::OptionBool$new(
                "item",
                item,
                default=FALSE)
            private$..post <- jmvcore::OptionBool$new(
                "post",
                post,
                default=FALSE)
            private$..gamma <- jmvcore::OptionBool$new(
                "gamma",
                gamma,
                default=FALSE)
            private$..member <- jmvcore::OptionBool$new(
                "member",
                member,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..covs)
            self$.addOption(private$..group)
            self$.addOption(private$..nc)
            self$.addOption(private$..nclust)
            self$.addOption(private$..nb)
            self$.addOption(private$..fit)
            self$.addOption(private$..comp1)
            self$.addOption(private$..rel1)
            self$.addOption(private$..margin)
            self$.addOption(private$..cla)
            self$.addOption(private$..cross)
            self$.addOption(private$..co)
            self$.addOption(private$..gof)
            self$.addOption(private$..ci)
            self$.addOption(private$..item)
            self$.addOption(private$..post)
            self$.addOption(private$..gamma)
            self$.addOption(private$..member)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        covs = function() private$..covs$value,
        group = function() private$..group$value,
        nc = function() private$..nc$value,
        nclust = function() private$..nclust$value,
        nb = function() private$..nb$value,
        fit = function() private$..fit$value,
        comp1 = function() private$..comp1$value,
        rel1 = function() private$..rel1$value,
        margin = function() private$..margin$value,
        cla = function() private$..cla$value,
        cross = function() private$..cross$value,
        co = function() private$..co$value,
        gof = function() private$..gof$value,
        ci = function() private$..ci$value,
        item = function() private$..item$value,
        post = function() private$..post$value,
        gamma = function() private$..gamma$value,
        member = function() private$..member$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..covs = NA,
        ..group = NA,
        ..nc = NA,
        ..nclust = NA,
        ..nb = NA,
        ..fit = NA,
        ..comp1 = NA,
        ..rel1 = NA,
        ..margin = NA,
        ..cla = NA,
        ..cross = NA,
        ..co = NA,
        ..gof = NA,
        ..ci = NA,
        ..item = NA,
        ..post = NA,
        ..gamma = NA,
        ..member = NA,
        ..plot1 = NA)
)

mlcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        fit = function() private$.items[["fit"]],
        comp1 = function() private$.items[["comp1"]],
        rel1 = function() private$.items[["rel1"]],
        margin = function() private$.items[["margin"]],
        cla = function() private$.items[["cla"]],
        cross = function() private$.items[["cross"]],
        gof = function() private$.items[["gof"]],
        ci = function() private$.items[["ci"]],
        member = function() private$.items[["member"]],
        item = function() private$.items[["item"]],
        plot1 = function() private$.items[["plot1"]],
        text3 = function() private$.items[["text3"]],
        text2 = function() private$.items[["text2"]],
        text4 = function() private$.items[["text4"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel LCA",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Model information"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Model fit",
                rows=1,
                visible="(fit)",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                refs="glca",
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="comp1",
                title="Absolute model fit for cluster",
                visible="(comp1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rel1",
                title="Relative model fit for cluster",
                visible="(rel1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="margin",
                title="Marginal prevalences for latent clusters",
                visible="(margin)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cla",
                title="Marginal prevalences for latent classes",
                refs="glca",
                visible="(cla)",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Probability"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cross",
                title="Class prevalences by cluster",
                refs="glca",
                visible="(cross)",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="gof",
                title="Goodness of fit for coefficients",
                visible="(gof)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="caic", 
                        `title`="CAIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="entropy", 
                        `title`="Entropy", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ci",
                title="Equality of coefficients",
                visible="(ci)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="para", 
                        `title`="Parameter", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="dev", 
                        `title`="Deviance", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="member",
                title="Cluster membership",
                refs="glca",
                visible="(member)",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="item",
                title="Item response probabilities(Rho)",
                visible="(item)",
                items="(vars)",
                clearWith=list(
                    "vars",
                    "covs",
                    "nc",
                    "nb",
                    "group",
                    "nclust"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Probability of $key",
                    clearWith=list(
                        "vars",
                        "covs",
                        "nc",
                        "nb",
                        "group",
                        "nclust"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                width=700,
                height=700,
                renderFun=".plot1",
                visible="(plot1)",
                refs="glca",
                clearWith=list(
                    "vars",
                    "nc",
                    "nb",
                    "group",
                    "covs",
                    "nclust")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text3",
                title="Logistic regression"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title="Class probability"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text4",
                title="Cluster probability(Gamma)"))}))

mlcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mlcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "mlca",
                version = c(1,0,0),
                options = options,
                results = mlcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multilevel LCA
#'
#' 
#' @param data the data as a data frame
#' @param vars .
#' @param covs .
#' @param group .
#' @param nc .
#' @param nclust .
#' @param nb .
#' @param fit .
#' @param comp1 .
#' @param rel1 .
#' @param margin .
#' @param cla .
#' @param cross .
#' @param co .
#' @param gof .
#' @param ci .
#' @param item .
#' @param post .
#' @param gamma .
#' @param member .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rel1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$margin} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cla} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cross} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gof} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ci} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$member} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$item} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text3} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text4} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
mlca <- function(
    data,
    vars,
    covs,
    group,
    nc = 2,
    nclust = 2,
    nb = 10,
    fit = TRUE,
    comp1 = FALSE,
    rel1 = FALSE,
    margin = FALSE,
    cla = FALSE,
    cross = FALSE,
    co = FALSE,
    gof = FALSE,
    ci = FALSE,
    item = FALSE,
    post = FALSE,
    gamma = FALSE,
    member = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mlca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mlcaOptions$new(
        vars = vars,
        covs = covs,
        group = group,
        nc = nc,
        nclust = nclust,
        nb = nb,
        fit = fit,
        comp1 = comp1,
        rel1 = rel1,
        margin = margin,
        cla = cla,
        cross = cross,
        co = co,
        gof = gof,
        ci = ci,
        item = item,
        post = post,
        gamma = gamma,
        member = member,
        plot1 = plot1)

    analysis <- mlcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

