
# This file is automatically generated, you probably don't want to edit this

profileOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            mc = TRUE,
            angle = 0,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="profile",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..mc <- jmvcore::OptionBool$new(
                "mc",
                mc,
                default=TRUE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=45,
                default=0)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..mc)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        mc = function() private$..mc$value,
        angle = function() private$..angle$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..mc = NA,
        ..angle = NA,
        ..plot1 = NA)
)

profileResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileResults",
    inherit = jmvcore::Group,
    active = list(
        mc = function() private$.items[["mc"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Profile plot",
                refs="snowLatent")
            self$add(jmvcore::Table$new(
                options=options,
                name="mc",
                title="Variable means across group",
                visible="(mc)",
                clearWith=list(
                    "vars",
                    "group"),
                refs="snowLatent",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Profile plot",
                visible="(plot1)",
                width=600,
                height=450,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "group",
                    "angle")))}))

profileBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "profile",
                version = c(1,0,0),
                options = options,
                results = profileResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Profile plot
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group .
#' @param mc .
#' @param angle a number from 0 to 45 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mc$asDF}
#'
#' \code{as.data.frame(results$mc)}
#'
#' @export
profile <- function(
    data,
    vars,
    group,
    mc = TRUE,
    angle = 0,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("profile requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- profileOptions$new(
        vars = vars,
        group = group,
        mc = mc,
        angle = angle,
        plot1 = plot1)

    analysis <- profileClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

