
# This file is automatically generated, you probably don't want to edit this

radarOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "radarOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            vars = NULL,
            num = 4,
            plot = FALSE,
            width = 500,
            height = 500,
            plot1 = FALSE,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="radar",
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..num <- jmvcore::OptionInteger$new(
                "num",
                num,
                default=4,
                min=4)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..labels)
            self$.addOption(private$..vars)
            self$.addOption(private$..num)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..plot1)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        labels = function() private$..labels$value,
        vars = function() private$..vars$value,
        num = function() private$..num$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        plot1 = function() private$..plot1$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..labels = NA,
        ..vars = NA,
        ..num = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..plot1 = NA,
        ..width1 = NA,
        ..height1 = NA)
)

radarResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "radarResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Radar Chart")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Variables summary"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Individual chart",
                requiresData=TRUE,
                visible="(plot)",
                renderFun=".plot",
                refs="snowLatent",
                clearWith=list(
                    "vars",
                    "labels",
                    "num",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Multiple individual chart",
                requiresData=TRUE,
                visible="(plot1)",
                renderFun=".plot1",
                refs="snowLatent",
                clearWith=list(
                    "vars",
                    "labels",
                    "width1",
                    "height1")))}))

radarBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "radarBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "radar",
                version = c(1,0,0),
                options = options,
                results = radarResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Radar Chart
#'
#' 
#' @param data The data as a data frame.
#' @param labels .
#' @param vars .
#' @param num .
#' @param plot .
#' @param width .
#' @param height .
#' @param plot1 .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
radar <- function(
    data,
    labels,
    vars,
    num = 4,
    plot = FALSE,
    width = 500,
    height = 500,
    plot1 = FALSE,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("radar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(vars), vars, NULL))


    options <- radarOptions$new(
        labels = labels,
        vars = vars,
        num = num,
        plot = plot,
        width = width,
        height = height,
        plot1 = plot1,
        width1 = width1,
        height1 = height1)

    analysis <- radarClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

