
# This file is automatically generated, you probably don't want to edit this

rainOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rainOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            angle = 0,
            plot = FALSE,
            width = 500,
            height = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="rain",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        angle = function() private$..angle$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..angle = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA)
)

rainResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rainResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="raincloud plot")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="raincloud",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "group",
                    "angle",
                    "width",
                    "height")))}))

rainBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rainBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "rain",
                version = c(1,0,0),
                options = options,
                results = rainResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' raincloud plot
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot .
#' @param width .
#' @param height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
rain <- function(
    data,
    vars,
    group,
    angle = 0,
    plot = FALSE,
    width = 500,
    height = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rain requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rainOptions$new(
        vars = vars,
        group = group,
        angle = angle,
        plot = plot,
        width = width,
        height = height)

    analysis <- rainClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

