
# This file is automatically generated, you probably don't want to edit this

stepOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stepOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = list(
                list(label="L[2]", vars=list())),
            covs = NULL,
            regform = "L ~ Species",
            impu = "modal",
            method = "BCH",
            reg = FALSE,
            fit = FALSE,
            par = FALSE,
            regform1 = "L ~ Species",
            impu1 = "modal",
            method1 = "BCH",
            reg1 = FALSE, ...) {

            super$initialize(
                package="snowLatent",
                name="step",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(
                    list(label="L[2]", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "nominal",
                                "continuous"),
                            permitted=list(
                                "factor",
                                "numeric")))))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..regform <- jmvcore::OptionString$new(
                "regform",
                regform,
                default="L ~ Species")
            private$..impu <- jmvcore::OptionList$new(
                "impu",
                impu,
                options=list(
                    "modal",
                    "prob"),
                default="modal")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "naive",
                    "BCH",
                    "ML"),
                default="BCH")
            private$..reg <- jmvcore::OptionBool$new(
                "reg",
                reg,
                default=FALSE)
            private$..member <- jmvcore::OptionOutput$new(
                "member")
            private$..post <- jmvcore::OptionOutput$new(
                "post")
            private$..fit <- jmvcore::OptionBool$new(
                "fit",
                fit,
                default=FALSE)
            private$..par <- jmvcore::OptionBool$new(
                "par",
                par,
                default=FALSE)
            private$..regform1 <- jmvcore::OptionString$new(
                "regform1",
                regform1,
                default="L ~ Species")
            private$..impu1 <- jmvcore::OptionList$new(
                "impu1",
                impu1,
                options=list(
                    "modal",
                    "prob"),
                default="modal")
            private$..method1 <- jmvcore::OptionList$new(
                "method1",
                method1,
                options=list(
                    "naive",
                    "BCH",
                    "ML"),
                default="BCH")
            private$..reg1 <- jmvcore::OptionBool$new(
                "reg1",
                reg1,
                default=FALSE)

            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..regform)
            self$.addOption(private$..impu)
            self$.addOption(private$..method)
            self$.addOption(private$..reg)
            self$.addOption(private$..member)
            self$.addOption(private$..post)
            self$.addOption(private$..fit)
            self$.addOption(private$..par)
            self$.addOption(private$..regform1)
            self$.addOption(private$..impu1)
            self$.addOption(private$..method1)
            self$.addOption(private$..reg1)
        }),
    active = list(
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        regform = function() private$..regform$value,
        impu = function() private$..impu$value,
        method = function() private$..method$value,
        reg = function() private$..reg$value,
        member = function() private$..member$value,
        post = function() private$..post$value,
        fit = function() private$..fit$value,
        par = function() private$..par$value,
        regform1 = function() private$..regform1$value,
        impu1 = function() private$..impu1$value,
        method1 = function() private$..method1$value,
        reg1 = function() private$..reg1$value),
    private = list(
        ..factors = NA,
        ..covs = NA,
        ..regform = NA,
        ..impu = NA,
        ..method = NA,
        ..reg = NA,
        ..member = NA,
        ..post = NA,
        ..fit = NA,
        ..par = NA,
        ..regform1 = NA,
        ..impu1 = NA,
        ..method1 = NA,
        ..reg1 = NA)
)

stepResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stepResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        fit = function() private$.items[["fit"]],
        post = function() private$.items[["post"]],
        reg = function() private$.items[["reg"]],
        member = function() private$.items[["member"]],
        text1 = function() private$.items[["text1"]],
        reg1 = function() private$.items[["reg1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LCA/LPA 3-Step Analysis",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Goodness of fit",
                rows=1,
                visible="(fit)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc"),
                columns=list(
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="integer"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log-likelihood", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="gsq", 
                        `title`="G\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="post",
                title="Posterior probabilities",
                measureType="continuous",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc")))
            self$add(jmvcore::Table$new(
                options=options,
                name="reg",
                title="Logistic regression",
                visible="(reg)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "covs",
                    "nc",
                    "method",
                    "impu",
                    "regform"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cla", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="va", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="co", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std.error", 
                        `type`="number"),
                    list(
                        `name`="wald", 
                        `title`="Wald", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="member",
                title="Class membership",
                measureType="nominal",
                varTitle="Membership",
                clearWith=list(
                    "factors",
                    "vars",
                    "nc")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="reg1",
                title="Logistic regression",
                visible="(reg1)",
                refs="slca",
                clearWith=list(
                    "factors",
                    "covs",
                    "nc",
                    "method1",
                    "impu1",
                    "regform1"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="cla", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="va", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="co", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std.error", 
                        `type`="number"),
                    list(
                        `name`="wald", 
                        `title`="Wald", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

stepBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stepBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "step",
                version = c(1,0,0),
                options = options,
                results = stepResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' LCA/LPA 3-Step Analysis
#'
#' 
#' @param data .
#' @param factors a list containing named lists that define the \code{label}
#'   of the factor and the \code{vars} that belong to that factor
#' @param covs .
#' @param regform .
#' @param impu .
#' @param method .
#' @param reg .
#' @param fit .
#' @param par .
#' @param regform1 .
#' @param impu1 .
#' @param method1 .
#' @param reg1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$post} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$member} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg1} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
step <- function(
    data,
    factors = list(
                list(label="L[2]", vars=list())),
    covs,
    regform = "L ~ Species",
    impu = "modal",
    method = "BCH",
    reg = FALSE,
    fit = FALSE,
    par = FALSE,
    regform1 = "L ~ Species",
    impu1 = "modal",
    method1 = "BCH",
    reg1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("step requires jmvcore to be installed (restart may be required)")

    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(covs), covs, NULL))


    options <- stepOptions$new(
        factors = factors,
        covs = covs,
        regform = regform,
        impu = impu,
        method = method,
        reg = reg,
        fit = fit,
        par = par,
        regform1 = regform1,
        impu1 = impu1,
        method1 = method1,
        reg1 = reg1)

    analysis <- stepClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

