
# This file is automatically generated, you probably don't want to edit this

wordOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            words = NULL,
            freq = NULL,
            minf = 1,
            maxw = 100,
            min = 1,
            max = 5,
            rot = 0.35,
            plot = TRUE,
            width = 500,
            height = 500,
            plot1 = FALSE,
            maxn = 10,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="snowLatent",
                name="word",
                requiresData=TRUE,
                ...)

            private$..words <- jmvcore::OptionVariable$new(
                "words",
                words,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..freq <- jmvcore::OptionVariable$new(
                "freq",
                freq,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..minf <- jmvcore::OptionInteger$new(
                "minf",
                minf,
                default=1,
                min=1)
            private$..maxw <- jmvcore::OptionInteger$new(
                "maxw",
                maxw,
                default=100,
                min=1)
            private$..min <- jmvcore::OptionNumber$new(
                "min",
                min,
                default=1,
                min=1)
            private$..max <- jmvcore::OptionNumber$new(
                "max",
                max,
                default=5,
                min=1)
            private$..rot <- jmvcore::OptionNumber$new(
                "rot",
                rot,
                default=0.35,
                min=0.1)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..maxn <- jmvcore::OptionNumber$new(
                "maxn",
                maxn,
                default=10,
                min=1)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..words)
            self$.addOption(private$..freq)
            self$.addOption(private$..minf)
            self$.addOption(private$..maxw)
            self$.addOption(private$..min)
            self$.addOption(private$..max)
            self$.addOption(private$..rot)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..plot1)
            self$.addOption(private$..maxn)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        words = function() private$..words$value,
        freq = function() private$..freq$value,
        minf = function() private$..minf$value,
        maxw = function() private$..maxw$value,
        min = function() private$..min$value,
        max = function() private$..max$value,
        rot = function() private$..rot$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        plot1 = function() private$..plot1$value,
        maxn = function() private$..maxn$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..words = NA,
        ..freq = NA,
        ..minf = NA,
        ..maxw = NA,
        ..min = NA,
        ..max = NA,
        ..rot = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..plot1 = NA,
        ..maxn = NA,
        ..width1 = NA,
        ..height1 = NA)
)

wordResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wordcloud analysis",
                refs="snowLatent")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Wordcloud plot",
                visible="(plot)",
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "words",
                    "freq",
                    "minf",
                    "max",
                    "min",
                    "rot",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Plot word frequencies",
                visible="(plot1)",
                renderFun=".plot1",
                requiresData=TRUE,
                clearWith=list(
                    "words",
                    "freq",
                    "maxn",
                    "width1",
                    "height1")))}))

wordBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowLatent",
                name = "word",
                version = c(1,0,0),
                options = options,
                results = wordResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wordcloud analysis
#'
#' 
#' @param data .
#' @param words .
#' @param freq .
#' @param minf .
#' @param maxw .
#' @param min .
#' @param max .
#' @param rot .
#' @param plot .
#' @param width .
#' @param height .
#' @param plot1 .
#' @param maxn .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
word <- function(
    data,
    words,
    freq,
    minf = 1,
    maxw = 100,
    min = 1,
    max = 5,
    rot = 0.35,
    plot = TRUE,
    width = 500,
    height = 500,
    plot1 = FALSE,
    maxn = 10,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("word requires jmvcore to be installed (restart may be required)")

    if ( ! missing(words)) words <- jmvcore::resolveQuo(jmvcore::enquo(words))
    if ( ! missing(freq)) freq <- jmvcore::resolveQuo(jmvcore::enquo(freq))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(words), words, NULL),
            `if`( ! missing(freq), freq, NULL))

    for (v in words) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in freq) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- wordOptions$new(
        words = words,
        freq = freq,
        minf = minf,
        maxw = maxw,
        min = min,
        max = max,
        rot = rot,
        plot = plot,
        width = width,
        height = height,
        plot1 = plot1,
        maxn = maxn,
        width1 = width1,
        height1 = height1)

    analysis <- wordClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

